version: '3'
services:
  sudoku:
    build:
      context: .
      dockerfile: ./apps/sudoku-angular/Dockerfile
    ports:
      - '4201:4201'
    container_name: sudoku
  sudoku-coop-backend:
    build:
      context: .
      dockerfile: ./apps/sudoku-coop-backend/Dockerfile
    ports:
      - '3333:3333'
    container_name: sudoku-coop-backend
